Metrics/LineLength:
  Max: 80

Style/Documentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true
  Enabled: true

Style/LambdaCall:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.4

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/DynamicFindBy:
  Whitelist:
    - find_by_graphql_id
    - find_by_graphql_id!

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: percent

Naming/PredicateName:
  NameWhitelist:
    - has_connection

Style/TrailingCommaInArguments:
  # If `comma`, the cop requires a comma after the last argument, but only for
  # parenthesized method calls where each argument is on its own line.
  # If `consistent_comma`, the cop requires a comma after the last argument,
  # for all parenthesized method calls with arguments.
  EnforcedStyleForMultiline: consistent_comma
